package:
  name: 7za
  version: "15.05"

source:
  fn: 7z1505-extra.7z # [win64]
  url: http://downloads.sourceforge.net/sevenzip/7z1505-extra.7z # [win64]
  sha1: 0837fe63ede13eadf4442eda7e275c6c1e5731a8 # [win64]
  md5: 3420fb5bfd55bcc26d8c0d4a42d39fd7 # [win64]

build:
  number: 1

requirements:
  build:
    # This package requires an earlier version of 7za but conda-build doesn't
    # allow that sort of dependency.
    # https://github.com/conda/conda-build/blob/master/
    # conda_build/metadata.py#L343
    # - 7za ==9.20

test:
  commands:
    - 7za | findstr 7-Zip # [win64]

about:
  home: http://www.7-zip.org
  license: LGPL
  summary: 7-Zip is a file archiver with a high compression ratio.
