package:
  name: google-api-python-client
  version: "1.4.1"

source:
  fn: google-api-python-client-1.4.1.tar.gz
  url: https://pypi.python.org/packages/source/g/google-api-python-client/google-api-python-client-1.4.1.tar.gz
  md5: 3e2cf16cf5502f6315aaf2fc8f1d7437

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - httplib2 >=0.8
    - oauth2client >=1.4.6
    - six >=1.6.1
    - uritemplate >=0.6

  run:
    - python
    - httplib2 >=0.8
    - oauth2client >=1.4.6
    - six >=1.6.1
    - uritemplate >=0.6

test:
  imports:
    - apiclient
    - googleapiclient

about:
  home: http://github.com/google/google-api-python-client/
  license: Apache Software License
  summary: 'Google API Client Library for Python'
