package:
  name: git
  version: "v2.4.6.windows.1"

source:
  fn: PortableGit-2.4.6-5th-release-candidate-64-bit.7z.exe  # [win64]
  url:
    "https://github.com/git-for-windows/git/releases/download/\
    v2.4.6.windows.1/\
    PortableGit-2.4.6-5th-release-candidate-64-bit.7z.exe" # [win64]


about:
  home: https://github.com/git-for-windows/git
  summary: A fork of Git containing Windows-specific patches.
  license: GPLv2
# http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline
