package:
  name: winshell
  version: "0.6"

source:
  fn: winshell-0.6.zip
  url: https://pypi.python.org/packages/source/w/winshell/winshell-0.6.zip
  md5: 378164955ff8511eaebc64fda8a04d77

requirements:
  build:
    - python

  run:
    - python

about:
  home: https://github.com/tjguk/winshell
  license: http://www.opensource.org/licenses/mit-license.php
  summary: 'Windows shell functions'
