package:
  name: 7za
  version: "9.20"
  # More recent versions than 9.20 are not available as zip files only .7z,
  # .exe or .msi files. 9.20 is the latest stable version.

source:
  fn: 7za920.zip # [win]
  url: http://downloads.sourceforge.net/sevenzip/7za920.zip # [win]
  sha1: 9ce9ce89ebc070fea5d679936f21f9dde25faae0 # [win]
  md5: 2fac454a90ae96021f4ffc607d4c00f8 # [win]

build:
  number: 1

test:
  commands:
    - 7za | findstr 7-Zip # [win]

about:
  home: http://www.7-zip.org
  license: LGPL
  summary: 7-Zip is a file archiver with a high compression ratio.
