package:
  name: uritemplate
  version: "0.6"

source:
  fn: uritemplate-0.6.tar.gz
  url: https://pypi.python.org/packages/source/u/uritemplate/uritemplate-0.6.tar.gz
  md5: ecfc1ea8d62c7f2b47aad625afae6173

build:
  number: 1

requirements:
  build:
    - python
    - simplejson >=2.5.0

  run:
    - python
    - simplejson >=2.5.0

test:
  imports:
    - uritemplate

about:
  home: http://github.com/uri-templates/uritemplate-py/
  license: Apache Software License
  summary: 'URI Templates'
