package:
  name: pep8-naming
  version: "0.3.3"

source:
  fn: pep8-naming-0.3.3.tar.gz
  url:
    "https://pypi.python.org/packages/source/p/pep8-naming/\
    pep8-naming-0.3.3.tar.gz"
  md5: 566f05660200993191312d51cd5a6cc9

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

about:
  home: https://github.com/flintwork/pep8-naming
  license: MIT License
  summary: 'Check PEP-8 naming conventions, plugin for flake8'
