package:
  name: pyasn1-modules
  version: "0.0.7"

source:
  fn: pyasn1-modules-0.0.7.tar.gz
  url: "https://pypi.python.org/packages/source/p/pyasn1-modules/\
    pyasn1-modules-0.0.7.tar.gz"
  md5: 9e92623a86709a77d43d406612ad7389

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - pyasn1 >=0.1.8

  run:
    - python
    - pyasn1 >=0.1.8

test:
  imports:
    - pyasn1_modules

about:
  home: http://sourceforge.net/projects/pyasn1/
  license: BSD License
  summary: 'A collection of ASN.1-based protocols modules.'
